// Pure, deterministic config.toml generation for SSH onboarding.
//
// Renders a valid easy-failover `config.toml` string from the operator-supplied
// fields, per `docs/config-reference.md`. This module is intentionally pure (no
// I/O, no ssh2, no secrets) so it is trivially unit-testable and deterministic:
// the same `ConfigInput` always renders byte-for-byte the same string.
//
// The generated config matches a packaged install's auto-provisioned defaults:
// real VIP mutation is ON, and the status/config API is enabled on 0.0.0.0 in
// write mode (a token file generated alongside the config authenticates writes).
// The node ships a real VIP here, so it participates immediately. Operators can
// still override the `[api]` fields.

import type { ConfigInput } from "./types";

/** Defaults that mirror `docs/config-reference.md`. */
const DEFAULTS = {
  priority: 100,
  heartbeat: {
    bind: "0.0.0.0:7432",
    intervalMs: 1000,
    timeoutMs: 3000
  },
  health: {
    intervalMs: 1000,
    timeoutMs: 2000
  },
  election: {
    requireQuorum: false,
    preempt: true
  },
  api: {
    enabled: true,
    bind: "0.0.0.0:8743",
    readOnly: false
  },
  authTokenFile: "/etc/easy-failover/api.token"
} as const;

/** Render a string value as a quoted TOML basic string. */
function tomlString(value: string): string {
  // Escape backslashes, double quotes, and the control characters TOML basic
  // strings forbid unescaped. Keeps generated TOML valid for arbitrary input.
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

function tomlBool(value: boolean): string {
  return value ? "true" : "false";
}

/**
 * Validate the minimal invariants config generation depends on. This is a fast,
 * server-side pre-check; the authoritative check remains the on-target
 * `easy-failover --config ... --validate-config`.
 */
export function validateConfigInput(input: ConfigInput): string[] {
  const errors: string[] = [];

  if (!input.vip || input.vip.address.trim().length === 0) {
    errors.push("vip.address is required and must be non-empty");
  }
  if (!input.vip || input.vip.interface.trim().length === 0) {
    errors.push("vip.interface is required and must be non-empty");
  }
  if (input.priority !== undefined && (!Number.isInteger(input.priority) || input.priority <= 0)) {
    errors.push("priority must be a positive integer");
  }
  // Zero peers is allowed (clean-slate / single-node); the onboarding flow normally
  // fills these in automatically from the current node's cluster (see cluster.ts).
  if (Array.isArray(input.peers)) {
    input.peers.forEach((peer, index) => {
      if (!peer.id || peer.id.trim().length === 0) {
        errors.push(`peers[${index}].id is required and must be non-empty`);
      }
      if (!peer.address || peer.address.trim().length === 0) {
        errors.push(`peers[${index}].address is required and must be non-empty`);
      }
    });
  }

  const hb = input.heartbeat;
  if (hb) {
    if (hb.intervalMs !== undefined && (!Number.isInteger(hb.intervalMs) || hb.intervalMs <= 0)) {
      errors.push("heartbeat.intervalMs must be a positive integer");
    }
    if (hb.timeoutMs !== undefined && (!Number.isInteger(hb.timeoutMs) || hb.timeoutMs <= 0)) {
      errors.push("heartbeat.timeoutMs must be a positive integer");
    }
  }

  const health = input.health;
  if (health) {
    if (health.intervalMs !== undefined && (!Number.isInteger(health.intervalMs) || health.intervalMs <= 0)) {
      errors.push("health.intervalMs must be a positive integer");
    }
    if (health.timeoutMs !== undefined && (!Number.isInteger(health.timeoutMs) || health.timeoutMs <= 0)) {
      errors.push("health.timeoutMs must be a positive integer");
    }
  }

  const api = input.api;
  if (api?.enabled === true) {
    const bind = api.bind ?? DEFAULTS.api.bind;
    if (bind.trim().length === 0) {
      errors.push("api.bind is required when api.enabled = true");
    }
  }

  return errors;
}

/**
 * Render a `config.toml` string from the request fields. Deterministic and pure.
 *
 * Notes:
 * - `node_id` is only emitted when provided; a blank node_id is omitted so the
 *   daemon's hostname default applies on the target.
 * - `[heartbeat]`/`[health]`/`[election]` are only emitted when the operator
 *   overrode at least one field. `[api]` and `[mutation_safety]` are ALWAYS
 *   emitted with the packaged-install defaults (API on / mutation on).
 */
export function generateConfigToml(
  input: ConfigInput,
  options: { authTokenFile?: string } = {}
): string {
  const lines: string[] = [];
  const authTokenFile = options.authTokenFile ?? DEFAULTS.authTokenFile;

  lines.push("# Generated by easy-failover dashboard SSH onboarding.");
  lines.push("# Matches a packaged install: real VIP mutation on, API on (write mode).");
  lines.push("");

  // Top-level keys.
  const nodeId = input.nodeId?.trim();
  if (nodeId) {
    lines.push(`node_id = ${tomlString(nodeId)}`);
  }
  lines.push(`priority = ${input.priority ?? DEFAULTS.priority}`);
  lines.push("");

  // VIP (required).
  lines.push("[vip]");
  lines.push(`address = ${tomlString(input.vip.address)}`);
  lines.push(`interface = ${tomlString(input.vip.interface)}`);
  lines.push("");

  // Peers (required, at least one).
  for (const peer of input.peers) {
    lines.push("[[peers]]");
    lines.push(`id = ${tomlString(peer.id)}`);
    lines.push(`address = ${tomlString(peer.address)}`);
    lines.push("");
  }

  // Heartbeat (optional).
  if (input.heartbeat) {
    const hb = input.heartbeat;
    lines.push("[heartbeat]");
    lines.push(`bind = ${tomlString(hb.bind ?? DEFAULTS.heartbeat.bind)}`);
    lines.push(`interval_ms = ${hb.intervalMs ?? DEFAULTS.heartbeat.intervalMs}`);
    lines.push(`timeout_ms = ${hb.timeoutMs ?? DEFAULTS.heartbeat.timeoutMs}`);
    lines.push("");
  }

  // Health (optional).
  if (input.health) {
    const health = input.health;
    lines.push("[health]");
    if (health.command !== undefined) {
      lines.push(`command = ${tomlString(health.command)}`);
    }
    lines.push(`interval_ms = ${health.intervalMs ?? DEFAULTS.health.intervalMs}`);
    lines.push(`timeout_ms = ${health.timeoutMs ?? DEFAULTS.health.timeoutMs}`);
    lines.push("");
  }

  // Election (optional).
  if (input.election) {
    const election = input.election;
    lines.push("[election]");
    lines.push(`require_quorum = ${tomlBool(election.requireQuorum ?? DEFAULTS.election.requireQuorum)}`);
    lines.push(`preempt = ${tomlBool(election.preempt ?? DEFAULTS.election.preempt)}`);
    lines.push("");
  }

  // API — on by default, bound to all interfaces, in write mode, matching a
  // packaged install so the dashboard can reach the node. When write mode is on,
  // a token file (generated alongside this config) authenticates writes.
  const apiEnabled = input.api?.enabled ?? DEFAULTS.api.enabled;
  const apiBind = input.api?.bind ?? DEFAULTS.api.bind;
  const apiReadOnly = input.api?.readOnly ?? DEFAULTS.api.readOnly;
  lines.push("[api]");
  lines.push(`enabled = ${tomlBool(apiEnabled)}`);
  lines.push(`bind = ${tomlString(apiBind)}`);
  lines.push(`read_only = ${tomlBool(apiReadOnly)}`);
  if (!apiReadOnly) {
    lines.push(`auth_token_file = ${tomlString(authTokenFile)}`);
  }
  lines.push("");

  // Mutation safety — real VIP movement is ON, matching a packaged install. The
  // node has a configured VIP here, so it participates in failover immediately.
  lines.push("[mutation_safety]");
  lines.push("allow_network_mutation = true");
  lines.push("");

  return lines.join("\n");
}
